services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - ./extraction:/app/extraction
    environment:
      - COMMIT_ID
      - COMMIT_TIME
      - COMMIT_MESSAGE

  extract:
    build: ./extract_scripts
    volumes:
      - ./extraction:/app/extraction

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
