services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
     - ./extraction:/app/extraction
    environment:
      - COMMIT_ID
  extract:
    build: ./extract_scripts
    volumes:
      - ./extraction:/app/extraction
