name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: 
      name: production

    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Hetzner
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.IP_ADDRESS }} << 'EOF'
          set -e
          echo "Pulling latest code from GitHub..."
          if [ ! -d /root/local-local ]; then
            mkdir /root/local-local
            git clone https://github.com/conorfennell/local-local.git /root/local-local
          else
            cd /root/local-local
            git fetch --all
            git reset --hard origin/main
          fi
          
          echo "Building the project..."
          cd /root/local-local
          docker-compose up --build -d # Replace with your actual build script or commands
        EOF
