name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: 
      name: production

    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Hetzner
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.IP_ADDRESS }} << 'EOF'
          set -e
          echo "Pulling latest code from GitHub..."
          if [ ! -d /root/local-local ]; then
            mkdir /root/local-local
            git clone https://github.com/conorfennell/local-local.git /root/local-local
          else
            cd /root/local-local
            git fetch --all
            git reset --hard origin/main
          fi
          
          echo "Building the project..."
          cd /root/local-local
          # Get the latest commit details
          COMMIT_ID=$(git rev-parse --short HEAD)
          COMMIT_TIME=$(git log -1 --format=%cd --date=iso)
          COMMIT_MESSAGE=$(git log -1 --format=%s)

          # Create an .env file with the commit details
          echo "COMMIT_ID=$COMMIT_ID" > .env
          echo "COMMIT_TIME=$COMMIT_TIME" >> .env
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> .env
          docker compose --env-file .env up --build -d
        EOF
